services:
  - type: web
    name: tirkai
    runtime: docker
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    healthCheckPath: /api/health
    autoDeploy: true
